config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "users#show"

  resources :locations, only: [:new, :create]
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  has_and_belongs_to_many :users
  belongs_to :creator, class_name: 'User', foreign_key: 'creator_id'

  validates_presence_of :name, :latitude, :longitude
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_and_belongs_to_many :locations
  has_many :my_location, class_name: 'Location'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :authenticate_user!

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)
    @location.creator = current_user
    respond_to do |format|
      if @location.save
        format.html  { redirect_to(user_path(current_user),
                      :notice => 'location was successfully created.') }
      else
        format.html  { render :action => "new" }
      end
    end
  end

  private
  def location_params
    params.require(:location).permit(:latitude, :longitude, :name, :public, user_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = params[:id] ? User.find(params[:id]) : current_user

    if @user == current_user
      @locations = Location.where(creator: @user)
      @locations_shared = @user.locations
    else
      @locations_shared = Location.where(creator: @user).where(public: true)
    end
    @users = User.where.not(id: @user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title LocationShare
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{:src => "https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v5.3.0/build/ol.js"}
    %link{:href => "https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v5.3.0/css/ol.css", :rel => "stylesheet"}

  %body
    = yield(:head_tags)
    = render 'shared/nav'
    -if notice
      %p.notice.alert.alert-success= notice
    - if alert
      %p.alert.alert-danger= alert
    = yield

app/views/locations/_form.html.haml
.location-form
  = simple_form_for @location do |f|
    .form-group
      = label_tag :name
      = f.input :name, class: 'form-control', label: false, required: true
    .form-group
      = label_tag :latitude
      = f.input :latitude, class: 'form-control', label: false, required: true
    .form-group
      = label_tag :longitude
      = f.input :longitude, class: 'form-control', label: false, required: true
    = f.input :public, as: :boolean
    .form-group
      = label_tag 'Users to share location with'
      = f.association :users, collection: User.where.not(id: current_user.id).map{|u| [u.email, u.id]}, class: 'form-control', label: false
    = f.button :submit, class: 'btn btn-secondary'

app/views/locations/new.html.haml
.title-location Add new location

= render 'form'

app/views/shared/_nav.html.haml
.navbar.navbar-expand-md.navbar-dark.bg-dark
  %ul.navbar-nav.mr-auto
    %li.nav-item.active
      .nav-link LocationShare
  - if user_signed_in?
    %ul.navbar-nav.ml-auto
      %li.nav-item.active
        = link_to 'New Location', new_location_path, class: 'nav-link'
      %li.nav-item.active
        = link_to 'Home', user_path(current_user), class: 'nav-link'
      %li.nav-item.active
        = link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link'

app/views/users/show.html.haml
.container-fluid
  .row
    .col-4
      .accordian#lists
        - if @locations.present? && @user == current_user
          .card
            .card-header#my-locations
              .mb-0
                .title-user(data-toggle="collapse" data-target="#my-locations-list" aria-expanded="true" aria-controls="my-locations-list") My locations
            .collapse#my-locations-list(aria-labelledby="my-locations" data-parent="#lists")
              .card-body
                %ul.list-group
                  - @locations.each do |location|
                    %li.list-group-item.list-group-item-light.location-name{'data-latitude':location.latitude, 'data-longitude':location.longitude}= location.name

        - if @locations_shared.present?
          .card
            .card-header#locations-shared
              .mb-0
                .title-user(data-toggle="collapse" data-target="#shared-locations-list" aria-expanded="true" aria-controls="shared-locations-list") Locations shared
            .collapse#shared-locations-list(aria-labelledby="locations-shared" data-parent="#lists")
              .card-body
                %ul.list-group
                  - @locations_shared.each do |location_shared|
                    %li.list-group-item.list-group-item-light.location-name{'data-latitude':location_shared.latitude, 'data-longitude':location_shared.longitude}= location_shared.name

        - if @user == current_user
          .card
            .card-header#users
              .mb-0
                .title-user(data-toggle="collapse" data-target="#users-list" aria-expanded="true" aria-controls="users-list") Other users
            .collapse#users-list(aria-labelledby="users" data-parent="#lists")
              .card-body
                %ul.list-group
                  - @users.each do |user|
                    %li.list-group-item.list-group-item-light= link_to(user.email, user_path(user))

    .col
      #map.map

- if @locations.present? || @locations_shared.present?
  - locations = @locations.to_a + @locations_shared.to_a
  - provide :head_tags do
    :javascript
      if( document.readyState === 'complete' ) {
        initMap(#{locations.map{|l| [l.longitude, l.latitude]}})
      } else {
        document.addEventListener('DOMContentLoaded', function () {
          initMap(#{locations.map{|l| [l.longitude, l.latitude]}})
        });
      }